name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install composer
        run: composer install

      - name: checkFolder
        run: ls vendor/bin
      - name: PHPUnit Tests
        run:  sudo vendor/bin/phpunit src/tests/Unit/UserTest.php