name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6
        with:
          dev: no
          args: --profile --ignore-platform-reqs

      - name: checkFolder
        run: ls
      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        env:
          TEST_NAME: Scarlett
        with:
          bootstrap: vendor/autoload.php
          configuration: ./test/phpunit.xml
          args: --coverage-text